<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.14.1 setup script
 * Date: Fri, 12 Feb 2016 18:39:11 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: Main Server [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Main Server';
$cfg['Servers'][$i]['host'] = '46.101.195.200';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'wordpress';
$cfg['Servers'][$i]['password'] = 'w2M68NdpLD';

/* End of servers configuration */

$cfg['blowfish_secret'] = '56be264b6ca0e2.92091118';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>